// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwsMRvj1xIHIh_fVe7q2casQcO6KMpD2E',
    appId: '1:1045723053078:web:75c3d174e61b3d81abc937',
    messagingSenderId: '1045723053078',
    projectId: 'r-d-flutter-course-project',
    authDomain: 'r-d-flutter-course-project.firebaseapp.com',
    storageBucket: 'r-d-flutter-course-project.firebasestorage.app',
    measurementId: 'G-MQTY814SDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVBCtqTiKeXMOr9JVY7AGc1Ofxp1SzQys',
    appId: '1:1045723053078:android:c77cb0ae6807074babc937',
    messagingSenderId: '1045723053078',
    projectId: 'r-d-flutter-course-project',
    storageBucket: 'r-d-flutter-course-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqG2oreBb-MDVwV4qFddtpBKWjEx78CKw',
    appId: '1:1045723053078:ios:69313c41da485fe5abc937',
    messagingSenderId: '1045723053078',
    projectId: 'r-d-flutter-course-project',
    storageBucket: 'r-d-flutter-course-project.firebasestorage.app',
    iosBundleId: 'com.example.rDFlutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqG2oreBb-MDVwV4qFddtpBKWjEx78CKw',
    appId: '1:1045723053078:ios:69313c41da485fe5abc937',
    messagingSenderId: '1045723053078',
    projectId: 'r-d-flutter-course-project',
    storageBucket: 'r-d-flutter-course-project.firebasestorage.app',
    iosBundleId: 'com.example.rDFlutterCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwsMRvj1xIHIh_fVe7q2casQcO6KMpD2E',
    appId: '1:1045723053078:web:029dafb17212dc87abc937',
    messagingSenderId: '1045723053078',
    projectId: 'r-d-flutter-course-project',
    authDomain: 'r-d-flutter-course-project.firebaseapp.com',
    storageBucket: 'r-d-flutter-course-project.firebasestorage.app',
    measurementId: 'G-252B8L4PXP',
  );
}
